### ISSUE TITLE
Publish Task per ProductFalvor

### ISSUE THREAD

**Issue by mikepenz** [SeongUgJung/gradle-play-publisher#2]
Hey. 

right now there's just a single publish task. so there's no way to publish different product falvors to the google play store. 

It would be great if there were seperate publish tasks let's say for free and release builds so i could publish them with a single gradle script.

it would also be great if the .apk file path was fetched through the build so it is not required to set it as static file path.

**Comment by SeongUgJung** [comment]
ok. good suggest.
I think to make task for assembleFlavorRelease.

task name is maybe....autoPublish?

haha. whatever I'll do future job.
